# Generated by Django 4.2.18 on 2025-01-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'permissions': (('development', 'Puede desarrollar'), ('scrum_master', 'Es Scrum Master'), ('visualizar_listado', 'visualizar listado'), ('superuser', 'superuser'))},
        ),
    ]
